### ISSUE TITLE
Можно ли оставить этот репозиторий публичным, или нужно сделать его приватным?

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/robotics21#1]
Давайте обсудим плюсы и минусы

Плюс публичного:
- доступна вкладка insights со статистикой
- любой желающий может создать тикет с ценной идеей, которую затем можно обсудить
- любой желающий может сделать пул реквест с исправлением косяков или добавлением ценного функционала (мы можем не принимать этот пул реквест)

Особенность публичного:
- виден всем желающим

Эта особенность - плюс или минус?

**Comment by bioidiad** [comment]
Я считаю, что надо делать публичным и агитирровать народ, как минимум из клуба робототехники, писать свои идеи и предложения. То что виден всем - не плохо. Даже если рак на горе свистнет и кто-то свистнет нашу идею и внедрит это где-то еще))

**Comment by Freimor** [comment]
Да пусть будет публичным, если кто захочет ознакомится или чем помочь. Это не секретная разработка)

**Comment by CptnGreen** [comment]
Отлично! Тогда оставляю публичным. 

Думаю, что через некоторое время, когда здесь будет уже не так пусто, можно будет скинуть ссылку на этот репозиторий в группу клуба, чтобы другие тоже принимали участие
