### ISSUE TITLE
Количество человек на бассейне. Обсуждение

### ISSUE THREAD

**Issue by Freimor** [CptnGreen/robotics21#13]
Лаборатория рассчитана на 6 рабочих мест + место за верстаком.
На какое количество человек мы будем рассчитывать? Какой режим работы?
Была идея что менторы смогут быть в лабе на протяжении 12 часов, сменяя друг друга.

**Comment by CptnGreen** [comment]
А что за менторы такие? Где их брать, как обучать, как вознаграждать за их труд? 

И не противоречит ли менторство концепциям Школы (самообучение, самостоятельный поиск информации)?

Может быть, ни менторы, ни даже дежурные, в лабе и не нужны, а достаточно камер?

И 6 рабочих мест - это очень мало, нужно больше. Может быть, робо-бассейну отдавать все переговорки?

**Comment by Freimor** [comment]
Менторы это люди которые следят за процессом (техника безопасности). Лаборантами еще называются
6 мест пока все что у нас есть. Пока узнаю, где мы сможем еще людей разместить

**Comment by Freimor** [comment]
Предлагаю ориентироваться на 6 человек для первого теста. Отработаем для 6-ти, легче будет заскелить до нужного количества

**Comment by bioidiad** [comment]
Если басик на 6 человек, то с 3д печатью все должно получится)

**Comment by CptnGreen** [comment]
Тогда решено - самый первый бассейн из расчёта на 6 человек, потому что 6 рабочих мест.

Вообще формула получается простая - сколько удастся выбить рабочих мест, столько нужно и набирать на бассейн.

Закрываю это обсуждение. Насчёт менторов-лаборантов нужно создать отдельное
