### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by Freimor** [CptnGreen/robotics21#5]
Разработка документа, описывающего бассеин ветки электроники в школе 21
[Док](https://docs.google.com/document/d/1g8cQ9nFI2hlKurEX9umPlbqU8W0IIlw_AAfD2EV0HRg/edit?usp=sharing)

**Comment by CptnGreen** [comment]
@Freimor, имеется в виду, какие проекты будут после бассейна?

**Comment by Freimor** [comment]
@CptnGreen имеется в виду бассейн. Переименую для наглядности

**Comment by CptnGreen** [comment]
@Freimor, окей, только немного не понимаю, зачем нам гугл-документ.

Можно же создать прямо здесь соответствующий файлик, зачем плодить сущности без меры?

**Comment by bioidiad** [comment]
@CptnGreen @Freimor согласен, давайте тут все доделаем, потом при необходимости перенесем в доку
